# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - uses: actions/upload-artifact@v3
      with:
        name: Standard Library
        path: dcm4che-typeddicom-lib/dcm4che-typeddicom-lib-std/build/libs
        retention-days: 7
    - uses: actions/upload-artifact@v3
      with:
        name: Generator Gradle Plugin
        path: dcm4che-typeddicom-generator/dcm4che-typeddicom-java-generator-gradleplugin/build/libs
        retention-days: 7
    - uses: actions/upload-artifact@v3
      with:
        name: Library Skeleton
        path: dcm4che-typeddicom-skeleton/build/libs
        retention-days: 7
    - uses: actions/upload-artifact@v3
      with:
        name: Parser DTOs
        path: dcm4che-typeddicom-parser/dcm4che-typeddicom-parser-dtos/build/libs
        retention-days: 7
